local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node

return {
	s("fmt", {
		t({
			"---",
			"Language: Cpp",
			"BasedOnStyle: LLVM",
			"",
			"IndentWidth: 4",
			"TabWidth: 4",
			"UseTab: Never",
			"AccessModifierOffset: -4",
			"NamespaceIndentation: None",
			"WrapNamespaceBodyWithEmptyLines: Always",
			"IndentCaseLabels: false",
			"",
			"ColumnLimit: 80",
			"ReflowComments: true",
			"",
			"PointerAlignment: Left",
			"ReferenceAlignment: Pointer",
			"DerivePointerAlignment: false",
			"NumericLiteralCase:",
			"  Suffix: Lower",
			"",
			"BreakBeforeBraces: Attach",
			"AllowShortBlocksOnASingleLine: Never",
			"AllowShortCaseLabelsOnASingleLine: true",
			"AllowShortFunctionsOnASingleLine: Inline",
			"AllowShortIfStatementsOnASingleLine: Never",
			"AllowShortLambdasOnASingleLine: All",
			"LambdaBodyIndentation: Signature",
			"AllowShortLoopsOnASingleLine: false",
			"",
			"AlignAfterOpenBracket: true",
			"AlignOperands: DontAlign",
			"AlignConsecutiveAssignments: None",
			"AlignConsecutiveDeclarations: None",
			"AlignConsecutiveMacros: Consecutive",
			"AlignTrailingComments: true",
			"",
			"BinPackArguments: false",
			"BinPackParameters: false",
			"AllowAllArgumentsOnNextLine: false",
			"AllowAllParametersOfDeclarationOnNextLine: false",
			"BreakBeforeBinaryOperators: NonAssignment",
			"BreakBeforeTernaryOperators: true",
			"",
			"BreakConstructorInitializers: BeforeColon",
			"PackConstructorInitializers: CurrentLine",
			"AlwaysBreakTemplateDeclarations: Yes",
			"SpaceAfterTemplateKeyword: true",
			"SpaceBeforeCpp11BracedList: true",
			"BreakAfterOpenBracketBracedList: true",
			"BreakBeforeCloseBracketBracedList: true",
			"",
			"IncludeBlocks: Regroup",
			"SortIncludes: CaseSensitive",
			"IncludeCategories:",
			"  - Regex: '^\"'",
			"    Priority: 1",
			"  - Regex: '^<[a-z_]+>$'",
			"    Priority: 3",
			"  - Regex: '^<'",
			"    Priority: 2",
			"IncludeIsMainRegex: '(_test|_bench)?$'",
			"",
			"SortUsingDeclarations: Never",
			"FixNamespaceComments: true",
			"ShortNamespaceLines: 0",
			"MaxEmptyLinesToKeep: 1",
		}),
	}),

	s("tidy", {
		t({
			"---",
			"Checks:",
			"  - '-*'",
			"  - 'clang-diagnostic-*'",
			"  - 'clang-analyzer-*'",
			"  - 'bugprone-*'",
			"  - 'concurrency-*'",
			"  - 'cppcoreguidelines-*'",
			"  - 'misc-*'",
			"  - 'modernize-*'",
			"  - 'performance-*'",
			"  - 'readability-*'",
			"  - 'google-runtime-int'",
			"  - 'portability-restrict-system-includes'",
			"",
			"  - '-bugprone-easily-swappable-parameters'",
			"  - '-cppcoreguidelines-avoid-do-while'",
			"  - '-cppcoreguidelines-avoid-magic-numbers'",
			"  - '-cppcoreguidelines-init-variables'",
			"  - '-cppcoreguidelines-owning-memory'",
			"  - '-modernize-return-braced-init-list'",
			"  - '-modernize-use-auto'",
			"  - '-modernize-use-trailing-return-type'",
			"  - '-readability-function-size'",
			"  - '-readability-identifier-length'",
			"  - '-readability-magic-numbers'",
			"  - '-readability-named-parameter'",
			"  - '-readability-uppercase-literal-suffix'",
			"",
			"  - '-cppcoreguidelines-pro-bounds-avoid-unchecked-container-access'",
			"  - '-cppcoreguidelines-pro-bounds-constant-array-index'",
			"  - '-cppcoreguidelines-pro-bounds-pointer-arithmetic'",
			"",
			"  - '-modernize-use-std-format'",
			"  - '-modernize-use-std-print'",
			"",
			"WarningsAsErrors: ''",
			"HeaderFilterRegex: '.*'",
			"FormatStyle: file",
			"",
			"ExtraArgs:",
			"  - '-Wfunction-effects'",
			"  - '-Wperf-constraint-implies-noexcept'",
			"  - '-Wthread-safety'",
			"  - '-Wfloat-equal'",
			"  - '-Wdouble-promotion'",
			"  - '-Wimplicit-fallthrough'",
			"  - '-Wvla'",
			"  - '-Wglobal-constructors'",
			"",
			"CheckOptions:",
			"  bugprone-unsafe-functions.CustomFunctions: >-",
			"    ^::std::(make_shared|allocate_shared)$,std::make_unique,heap-allocates and every shared_ptr copy is an atomic RMW;",
			"    ^::std::async$,,spawns a thread and its future blocks in the destructor;",
			"    ^::std::this_thread::sleep_(for|until)$,,wakeup latency is scheduler-bound; spin or block on the event source;",
			"    ^::(sleep|usleep|nanosleep)$,,wakeup latency is scheduler-bound; spin or block on the event source;",
			"    ^::std::chrono::system_clock::now$,std::chrono::steady_clock::now,wall clock can jump; measure latency on a monotonic clock;",
			"    ^::std::to_string$,std::to_chars,allocates a std::string;",
			"    ^::std::sto(i|l|ll|ul|ull|f|d|ld)$,std::from_chars,allocates and throws;",
			"    ^::(ato(i|l|ll|f)|strto(l|ll|ul|ull|f|d|ld))$,std::from_chars,locale-aware and slow;",
			"    ^::std::v?format$,std::format_to_n,returns an allocating std::string;",
			"    ^::std::thread::detach$,std::jthread,unjoined thread with no shutdown story",
			"  portability-restrict-system-includes.Includes: '*,-iostream,-sstream,-regex,-future,-any'",
			"",
			"  google-runtime-int.SignedTypePrefix: 'std::int'",
			"  google-runtime-int.UnsignedTypePrefix: 'std::uint'",
			"  google-runtime-int.TypeSuffix: '_t'",
			"  performance-for-range-copy.WarnOnAllAutoCopies: true",
			"  performance-inefficient-string-concatenation.StrictMode: true",
			"  bugprone-unused-return-value.AllowCastToVoid: true",
			"  cppcoreguidelines-pro-type-member-init.IgnoreArrays: true",
			"  cppcoreguidelines-special-member-functions.AllowSoleDefaultDtor: true",
			"  concurrency-mt-unsafe.FunctionSet: glibc",
			"",
			"  modernize-use-nullptr.NullMacros: 'NULL'",
			"  modernize-use-designated-initializers.IgnoreSingleElementAggregates: false",
			"  readability-braces-around-statements.ShortStatementLines: 0",
			"  readability-function-cognitive-complexity.Threshold: 25",
			"  readability-implicit-bool-conversion.AllowIntegerConditions: true",
			"  readability-implicit-bool-conversion.AllowPointerConditions: true",
			"  cppcoreguidelines-non-private-member-variables-in-classes.IgnoreClassesWithAllMemberVariablesBeingPublic: true",
			"  misc-non-private-member-variables-in-classes.IgnoreClassesWithAllMemberVariablesBeingPublic: true",
			"  misc-const-correctness.AnalyzePointers: false",
			"  misc-const-correctness.AnalyzeReferences: false",
			"  misc-const-correctness.AnalyzeValues: true",
			"",
			"  readability-identifier-naming.ClassCase: lower_case",
			"  readability-identifier-naming.StructCase: lower_case",
			"  readability-identifier-naming.EnumCase: lower_case",
			"  readability-identifier-naming.EnumConstantCase: lower_case",
			"  readability-identifier-naming.NamespaceCase: lower_case",
			"  readability-identifier-naming.FunctionCase: lower_case",
			"  readability-identifier-naming.VariableCase: lower_case",
			"  readability-identifier-naming.ParameterCase: lower_case",
			"  readability-identifier-naming.ConstantCase: lower_case",
			"  readability-identifier-naming.PrivateMemberCase: lower_case",
			"  readability-identifier-naming.PrivateMemberPrefix: 'm_'",
			"  readability-identifier-naming.ProtectedMemberCase: lower_case",
			"  readability-identifier-naming.ProtectedMemberPrefix: 'm_'",
			"  readability-identifier-naming.PublicMemberCase: lower_case",
			"  readability-identifier-naming.MacroDefinitionCase: UPPER_CASE",
			"  readability-identifier-naming.TypeAliasCase: lower_case",
			"  readability-identifier-naming.TemplateParameterCase: CamelCase",
		}),
	}),
}
