-- Palette-driven colorscheme: every color is a role from the active theme palette
-- (theme/palettes/*.lua, see theme/AGENTS.md). Load with `:colorscheme palette`.
-- Group layout seeded from lackluster.nvim (MIT, Copyright (c) 2024 Duncan Marsh).

local c = require("config.theme").palette()

vim.cmd.highlight("clear")
if vim.fn.exists("syntax_on") == 1 then
	vim.cmd.syntax("reset")
end
vim.o.termguicolors = true
vim.g.colors_name = "palette"

-- stylua: ignore
local groups = {
	-- Editor UI and legacy syntax groups
	Normal = { fg = c.fg_strong },
	Title = { fg = c.fg_dim },
	Whitespace = { fg = c.whitespace },
	NonText = { fg = c.fg_dim },
	SignColumn = { fg = c.fg_faint },
	CursorLine = { bg = c.surface },
	CursorLineNr = { fg = c.fg },
	LineNr = { fg = c.fg_faint },
	ColorColumn = { bg = c.surface },
	Search = { fg = c.bg, bg = c.accent_muted },
	CurSearch = { fg = c.bg, bg = c.fg_strong },
	IncSearch = { link = "CurSearch" },
	Substitute = { link = "Search" },
	VISUAL = { fg = c.bg, bg = c.fg_strong },
	VISUALNOS = { link = "VISUAL" },
	Folded = { fg = c.fg_faint },
	FoldColumn = { fg = c.fg_faint },
	Error = { fg = c.error },
	ModeMsg = { fg = c.fg_max },
	MoreMsg = { fg = c.fg_max },
	MsgArea = { fg = c.fg_max },
	ErrorMsg = { link = "Error" },
	WarningMsg = { fg = c.warning },
	NvimInternalError = { fg = c.error },
	healthError = { fg = c.error },
	healthSuccess = { fg = c.success },
	healthWarning = { fg = c.warning },
	StatusLine = { fg = c.fg_strong, bg = c.surface },
	StatusLineNC = { fg = c.fg_muted, bg = c.surface },
	Tabline = { fg = c.fg_faint, bg = c.surface },
	TablineSel = { fg = c.bg_alt, bg = c.fg_strong },
	TablineFill = { fg = c.fg, bg = c.statusbar },
	NormalFloat = {},
	FloatBorder = {},
	FloatTitle = { fg = c.fg_dim },
	Pmenu = { fg = c.fg_muted },
	PmenuSbar = { fg = c.border, bg = c.border },
	PmenuThumb = { fg = c.fg_dim, bg = c.fg_dim },
	PmenuSel = { fg = c.bg, bg = c.fg_strong },
	WinSeparator = { fg = c.fg_faint },
	EndOfBuffer = { fg = c.fg_faint },
	QuickFixLine = { fg = c.success },
	Identifier = { fg = c.syntax_type },
	Function = { fg = c.syntax_call },
	Type = { fg = c.syntax_type },
	Variable = { fg = c.syntax_variable },
	Statement = { fg = c.syntax_keyword },
	Special = { fg = c.syntax_special },
	Keyword = { fg = c.syntax_keyword },
	Conditional = { link = "Keyword" },
	Repeat = { link = "Keyword" },
	Label = { link = "Keyword" },
	Exception = { link = "Keyword" },
	PreProc = { link = "Keyword" },
	Constant = { fg = c.syntax_constant },
	String = { fg = c.syntax_string },
	Character = { link = "String" },
	Number = { link = "Constant" },
	Boolean = { link = "Constant" },
	Float = { link = "Constant" },
	Quote = { fg = c.syntax_string },
	Operator = { fg = c.syntax_punctuation },
	Delimiter = { fg = c.syntax_punctuation },
	MatchParen = { bg = c.border },
	Todo = { fg = c.fg_muted },
	Question = { fg = c.fg_muted },
	Comment = { fg = c.syntax_comment },
	SpecialComment = { fg = c.syntax_comment },
	DevIconDefault = { fg = c.fg_faint },
	Directory = { fg = c.fg_dim },

	-- Diagnostics
	DiagnosticOk = { fg = c.fg_faint },
	DiagnosticHint = { fg = c.fg_faint },
	DiagnosticInfo = { fg = c.fg_faint },
	DiagnosticWarn = { fg = c.fg_faint },
	DiagnosticError = { fg = c.error },
	DiagnosticDeprecated = { fg = c.fg_faint },
	DiagnosticUnnecessary = { fg = c.fg_faint },
	DiagnosticVirtualTextOk = { fg = c.fg_faint },
	DiagnosticVirtualTextHint = { fg = c.fg_faint },
	DiagnosticVirtualTextInfo = { fg = c.fg_faint },
	DiagnosticVirtualTextWarn = { fg = c.fg_faint },
	DiagnosticVirtualTextError = { fg = c.error },
	DiagnosticSignOk = { fg = c.success },
	DiagnosticSignInfo = { fg = c.fg_muted },
	DiagnosticSignHint = { fg = c.fg_muted },
	DiagnosticSignWarn = { fg = c.warning },
	DiagnosticSignError = { fg = c.error },
	DiagnosticSignDeprecated = { fg = c.warning },
	DiagnosticUnderlineWarn = { sp = c.warning, underline = true, undercurl = false },
	DiagnosticUnderlineInfo = { sp = c.fg_muted, underline = true, undercurl = false },
	DiagnosticUnderlineHint = { sp = c.fg_muted, underline = true, undercurl = false },
	DiagnosticUnderlineError = { sp = c.error, underline = true, undercurl = false },

	-- Spelling
	SpellBad = { underline = true, undercurl = false },
	SpellLocal = { link = "SpellBad" },
	SpellCap = { link = "SpellBad" },
	SpellRare = { link = "SpellBad" },

	-- Diff
	Added = { fg = c.success },
	Changed = { fg = c.fg_muted },
	Removed = { fg = c.warning },
	DiffAdd = { fg = c.success },
	DiffChange = { fg = c.fg_muted },
	DiffDelete = { fg = c.warning },
	DiffText = { fg = c.fg_dim },
	DiffAdded = { fg = c.success },
	DiffRemoved = { fg = c.warning },
	DiffChanged = { fg = c.fg_muted },
	DiffOldFile = { fg = c.fg_dim },
	DiffNewFile = { fg = c.success },
	DiffFile = { fg = c.fg_muted },
	DiffLine = { fg = c.fg_muted },
	DiffIndexLine = { fg = c.fg_dim },

	-- Treesitter captures
	["@keyword"] = { fg = c.syntax_keyword, bold = true, italic = false },
	["@keyword.return"] = { fg = c.syntax_return },
	["@keyword.exception"] = { fg = c.syntax_exception },
	["@attribute"] = { fg = c.syntax_keyword },
	["@type"] = { fg = c.syntax_type },
	["@type.definition"] = { fg = c.syntax_type_def },
	["@property"] = { fg = c.fg },
	["@label"] = { fg = c.fg_dim },
	["@variable"] = { fg = c.syntax_variable },
	["@variable.member"] = { fg = c.syntax_member },
	["@constant"] = { fg = c.syntax_constant },
	["@boolean"] = { fg = c.syntax_constant },
	["@number"] = { fg = c.syntax_constant },
	["@operator"] = { fg = c.syntax_punctuation },
	["@punctuation.bracket"] = { fg = c.syntax_punctuation },
	["@punctuation.special"] = { fg = c.syntax_punctuation },
	["@punctuation.delimiter"] = { fg = c.syntax_punctuation },
	["@constructor"] = { fg = c.syntax_punctuation },
	["@function"] = { link = "@keyword" },
	["@function.method"] = { fg = c.syntax_function },
	["@function.call"] = { fg = c.syntax_call },
	["@function.method.call"] = { fg = c.syntax_call },
	["@variable.parameter"] = { fg = c.syntax_param },
	["@string"] = { fg = c.syntax_string },
	["@character"] = { fg = c.syntax_string },
	["@string.escape"] = { fg = c.syntax_escape },
	["@string.special"] = { fg = c.syntax_escape },
	["@string.regexp"] = { fg = c.syntax_escape },
	["@comment"] = { fg = c.syntax_comment },
	["@comment.todo"] = { fg = c.fg_muted },
	["@comment.note"] = { fg = c.fg_muted },
	["@comment.warn"] = { fg = c.warning },
	["@comment.error"] = { fg = c.error },
	["@comment.documentation"] = { fg = c.syntax_comment },
	["@markup.heading"] = { fg = c.fg_dim },
	["@markup.quote"] = { fg = c.fg_muted },
	["@markup.strong"] = { fg = c.fg_faint, bold = true },
	["@markup.italic"] = { fg = c.fg_faint, italic = true },
	["@markup.strikethrough"] = { fg = c.fg_faint },
	["@markup.underline"] = { underline = true },
	["@markup.list"] = { fg = c.fg_faint },
	["@markup.list.checked"] = { fg = c.syntax_escape },
	["@markup.list.unchecked"] = { fg = c.error },
	["@markup.link"] = { fg = c.fg_muted },
	["@markup.link.label"] = { fg = c.fg_muted },
	["@markup.link.url"] = { fg = c.fg_faint },
	["@markup.math"] = { fg = c.fg_muted },
	["@tag"] = { fg = c.syntax_tag },
	["@tag.delimiter"] = { fg = c.syntax_tag },
	["@tag.attribute"] = { fg = c.fg_faint },
	["@type.builtin"] = { fg = c.syntax_type_builtin },
	["@tag.builtin"] = { fg = c.syntax_tag },
	["@variable.builtin"] = { fg = c.syntax_variable },
	["@function.builtin"] = { fg = c.syntax_builtin },
	["@module.builtin"] = { fg = c.syntax_builtin },
	["@constant.builtin"] = { fg = c.syntax_constant_builtin },
	["@diff.pluss"] = { fg = c.success },
	["@diff.minus"] = { fg = c.warning },
	["@diff.delta"] = { fg = c.fg_muted },
	["@string.special.symbol.clojure"] = { fg = c.syntax_type },
	["@property.json"] = { fg = c.fg_muted },
	["@property.yaml"] = { fg = c.fg_muted },
	["@property.toml"] = { fg = c.fg_muted },
	["@type.toml"] = { fg = c.fg_strong },
	["@property.css"] = { fg = c.fg_strong },
	["@tag.css"] = { fg = c.fg_strong },
	["@string.special.symbol.make"] = { fg = c.syntax_string },
	["@number.latex"] = { fg = c.fg_muted },

	-- LSP semantic tokens
	["@lsp.type.keyword"] = { link = "@keyword" },
	["@lsp.type.function"] = { link = "@function" },
	["@lsp.type.variable"] = { link = "@variable" },
	["@lsp.type.operator"] = { link = "@operator" },
	["@lsp.type.type"] = { link = "@type" },
	["@lsp.type.string"] = { link = "@string" },
	["@lsp.type.number"] = { link = "@number" },
	["@lsp.type.boolean"] = { link = "@boolean" },
	["@lsp.type.enumMember"] = { link = "@variable.member" },

	-- Filetype-specific legacy syntax
	lispFunc = { link = "@variable.parameter" },
	lispSymbol = { link = "@variable" },
	lispDecl = { link = "@keyword" },
	zshFunction = { fg = c.syntax_function },
	xmlTag = { fg = c.fg_dim },
	xmlTagName = { fg = c.fg_dim },
	xmlAttrib = { fg = c.fg_faint },
	htmlTagName = { fg = c.syntax_tag },
	texStatement = { fg = c.fg_dim },
	texDefCmd = { fg = c.fg_dim },
	texDefName = { fg = c.fg_dim },
	texDocType = { fg = c.fg_dim },
	texDocZone = { fg = c.fg_dim },
	texDocAbstract = { fg = c.fg_dim },
	texBeginEnd = { fg = c.fg_dim },
	cssMediaProp = { fg = c.fg_strong },
	cssTransitionProp = { fg = c.fg_strong },
	cssTextProp = { fg = c.fg_strong },
	cssBoxProp = { fg = c.fg_strong },
	cssFontProp = { fg = c.fg_strong },
	cssPositioningProp = { fg = c.fg_strong },
	cssBorderProp = { fg = c.fg_strong },
	cssBackgroundProp = { fg = c.fg_strong },
	cssTransformProp = { fg = c.fg_strong },
	markdownCodeDelimiter = { fg = c.success },
	markdownLinkDelimiter = { fg = c.fg_muted },
	markdownLinkTextDelimiter = { link = "@markup.link" },
	markdownLinkText = { link = "@markup.link" },
	markdownUrl = { link = "@markup.link.url" },
	sqlType = { fg = c.syntax_string },
	sqlKeyword = { fg = c.syntax_keyword },
	sqlStatement = { fg = c.syntax_keyword },
	sqlVariable = { fg = c.syntax_special },
	makeSpecial = { fg = c.syntax_special },
	markdownCode = {},
	markdownCodeBlock = {},

	-- Plugin: cmp
	CmpItemKind = { fg = c.fg },
	CmpItemKindSnippet = { fg = c.accent_muted },
	CmpItemAbbrDeprecated = { fg = c.fg_faint },

	-- Plugin: oil
	OilFile = { fg = c.fg_max },
	OilDir = { fg = c.fg_dim },
	OilDirIcon = { fg = c.fg_dim },
	OilLink = { fg = c.accent_muted },
	OilLinkTarget = { link = "OilLink" },
	OilSocket = { fg = c.fg_muted },
	OilCreate = { fg = c.success },
	OilCopy = { fg = c.success },
	OilRestore = { fg = c.success },
	OilDelete = { fg = c.warning },
	OilPurge = { fg = c.warning },
	OilTrash = { fg = c.warning },
	OilTrashSourcePath = { fg = c.warning },
	OilMove = { fg = c.fg_muted },
	OilChange = { fg = c.fg_muted },

	-- Plugin: render-markdown
	RenderMarkdownCode = {},
	RenderMarkdownCodeInline = { fg = c.fg_muted },
	RenderMarkdownCodeBorder = {},
	RenderMarkdownMath = { fg = c.fg_muted },

	-- Plugin: telescope
	TelescopeNormal = {},
	TelescopeBorder = {},
	TelescopeMatching = { fg = c.accent, bold = false, italic = false },
	TelescopeSelection = { fg = c.fg_strong, bg = c.border },
	TelescopePreviewLine = { fg = c.bg, bg = c.fg_bright },
	TelescopePreviewMatch = { link = "TelescopePreviewLine" },
	TelescopeTitle = { fg = c.fg_strong },
	TelescopeMultiSelection = { link = "TelescopeTitle" },
	TelescopeMultiIcon = { link = "TelescopeTitle" },
	TelescopePromptPrefix = { link = "TelescopeTitle" },
	TelescopePromptCounter = { fg = c.fg },
	TelescopeResultsNormal = {},
	TelescopeResultsSpecialComment = { link = "TelescopeResultsNormal" },
	TelescopeResultsDiffUntracked = { link = "TelescopeResultsNormal" },
	TelescopeResultsIdentifier = { link = "TelescopeResultsNormal" },
	TelescopeResultsDiffDelete = { link = "TelescopeResultsNormal" },
	TelescopeResultsDiffChange = { link = "TelescopeResultsNormal" },
	TelescopeResultsVariable = { link = "TelescopeResultsNormal" },
	TelescopeResultsOperator = { link = "TelescopeResultsNormal" },
	TelescopeResultsFunction = { link = "TelescopeResultsNormal" },
	TelescopeResultsConstant = { link = "TelescopeResultsNormal" },
	TelescopeResultsDiffAdd = { link = "TelescopeResultsNormal" },
	TelescopeResultsComment = { link = "TelescopeResultsNormal" },
	TelescopeResultsSymbol = { link = "TelescopeResultsNormal" },
	TelescopeResultsStruct = { link = "TelescopeResultsNormal" },
	TelescopeResultsNumber = { link = "TelescopeResultsNormal" },
	TelescopeResultsMethod = { link = "TelescopeResultsNormal" },
	TelescopeResultsLineNr = { link = "TelescopeResultsNormal" },
	TelescopeResultsField = { link = "TelescopeResultsNormal" },
	TelescopeResultsClass = { link = "TelescopeResultsNormal" },
	TelescopePreviewNormal = {},
	TelescopePreviewBorder = {},
	TelescopePromptBorder = {},
	TelescopeResultsBorder = {},
	TelescopePromptNormal = {},
}

for name, spec in pairs(groups) do
	vim.api.nvim_set_hl(0, name, spec)
end
