# GENERATED by theme/build.lua from theme/templates/zsh/themes/colors.zsh -- edit that instead.
export FZF_DEFAULT_OPTS="--color=fg:{{fg}},bg:-1,hl:{{accent}},fg+:{{fg_max}},bg+:{{surface}},hl+:{{accent}},gutter:-1,border:{{border}},separator:{{border}},scrollbar:{{fg_faint}},label:{{fg_muted}},prompt:{{fg_muted}},pointer:{{accent}},marker:{{success}},spinner:{{fg_muted}},info:{{fg_dim}},header:{{fg_dim}},query:{{fg_max}}"

# bat follows the terminal's 16 colors, which theme/build.lua also controls.
export BAT_THEME=ansi
