# GENERATED by theme/build.lua from theme/templates/zsh/themes/zsh.zsh-theme -- edit that instead.
PROMPT="%B%(?:%F{{{fg_dim}}}➜ :%F{{{fg_muted}}}➜ ) %F{{{fg_faint}}}%c%f%b"
PROMPT+=' $(git_prompt_info)'

ZSH_THEME_GIT_PROMPT_PREFIX="%B%F{{{fg_dim}}}git:(%F{{{fg_muted}}}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%f%b "
ZSH_THEME_GIT_PROMPT_DIRTY="%F{{{fg_dim}}}) %F{{{fg}}}✗"
ZSH_THEME_GIT_PROMPT_CLEAN="%F{{{fg_dim}}})"
