TS_SEARCH_PATHS=( "$HOME/personal" "$HOME/images" "$HOME/vault:0"
"$HOME/vault/books:1" "$HOME/vault/papers:1" "$HOME/dotfiles"
"$HOME/dotfiles/pi" "$HOME/school" "$HOME/sandbox" "$HOME/wb" "$HOME/.local"
"$HOME/.config:0" "$HOME/.codex:0" "$HOME/.ssh:0" "$HOME/.pi:0"
"$HOME/downloads" "$HOME/dotfiles/pi/picosystem" "$HOME/raw" "$HOME/media"
"$HOME/demo")

TS_EXTRA_SEARCH_PATHS=() 

TS_IGNORE_PATHS=()

TS_MAX_DEPTH=1
