TS_SEARCH_PATHS=( "$HOME/personal" "$HOME/images" "$HOME/vault" "$HOME/notes"
"$HOME/dotfiles" "$HOME/dotfiles/pi" "$HOME/school" "$HOME/sandbox"
"$HOME/comp-prog" "$HOME/.local" "$HOME/.config:0" "$HOME/.codex:0"
"$HOME/.ssh:0")

TS_EXTRA_SEARCH_PATHS=() 

TS_IGNORE_PATHS=()

TS_MAX_DEPTH=1
